disabled = false
locale = "en"
label = "English"
weight = 1
title = "SAHSOUHA"
body = "test"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = ""
copyright = "© TEZ - 2026"
logo = "img/waguribw.png"

[params.author]
name = "sahsouha"
imageQuality = 96
headline = "CyberSecurity is my Playstation"
bio = "ENSI Student & CTF Player"
image = "img/waguri.png"

[[params.author.links]]
email = "mailto:youremail@example.com"

[[params.author.links]]
github = "https://github.com/username"

[[params.author.links]]
twitter = "https://twitter.com/username"
