disabled = false
locale = "en"
label = "English"
weight = 1
title = "sah"
body = "test"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = ""
copyright = "© TEZ - 2026"
logo = "img/waguribw.png"

[params.author]
name = "Sahnoun"
imageQuality = 96
headline = "CyberSecurity is my PlayStation"
bio = "ENSI Student & CTF Player"
image = "img/selfie.png"

[[params.author.links]]
email = "mailto:work@sahnoun.dev"

[[params.author.links]]
github = "https://github.com/ENSI-Sahnoun"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/sahnounyoussef"
