disableImageOptimization = false
skills = [
  {name = "CTFs",               level = 5},
  {name = "C",                  level = 5},
  {name = "Python",             level = 5},
  {name = "Linux Bash",         level = 5},
  {name = "OSINT",              level = 4},
  {name = "C++",                level = 4},
  {name = "Git",                level = 4},
  {name = "Digital Forensics",  level = 4},
  {name = "HTML",               level = 4},
  {name = "CSS",                level = 4},
  {name = "HackTheBox",        level = 4},
  {name = "TryHackMe",         level = 4},
  {name = "Steganography",      level = 3},
  {name = "Java",               level = 3},
  {name = "MySQL",              level = 3},
  {name = "PHP",                level = 3},
  {name = "GitHub Copilot",     level = 3},
  {name = "DNS",                level = 3},
  {name = "VS Code",            level = 2},
  {name = "AWS Hosting",        level = 2},
  {name = "Adobe Premiere Pro", level = 2},
  {name = "Adobe Illustrator",  level = 2},
  {name = "Agentic AI",         level = 2},
  {name = "Prompt Engineering", level = 2},
  {name = "Antigravity",        level = 1},
]
defaultAppearance = "dark"
enableCodeCopy = false
autoSwitchAppearance = true
mainSections = ["writeups", "blog", "achievements", "ctfs", "projects"]
disableTextInHeader = true
colorScheme = "congo"
enableSearch = true
fingerprintAlgorithm = "sha512"
hotlinkFeatureImage = false
github_username = "ENSI-Sahnoun"
giteaDefaultServer = "https://git.fsfe.org"
disableImageOptimizationMD = false
forgejoDefaultServer = "https://v11.next.forgejo.org"
backgroundImageWidth = 2560
enableA11y = false
replyByEmail = false
enableStructuredBreadcrumbs = false
resume_url = "/resume"

[selineAnalytics]

[umamiAnalytics]

[taxonomyDefaults]
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showTermCount = false

[_appearance]
defaultAppearance = "dark"
autoSwitchAppearance = false
colorScheme = "congo"

[fonts]
fontUrl = "https://fonts.googleapis.com/css2?family=Story+Script&display=swap"
fontBody = "'Google Sans'"
fontHeading = "'Story Script'"
fontNavbar = ""
fontBodyFile = ""
fontHeadingFile = "fonts/moistlyvengionsdemo-regular.otf"

[rssnext]

[advertisement]

[firebase]

[general]
enableSearch = true
enableStructuredBreadcrumbs = true
highlightCurrentMenuArea = true
fingerprintAlgorithm = "sha512"
smartTOC = true
smartTOCHideUnfocusedChildren = false
enableCodeCopy = true
disableTextInHeader = true

[articleDefaults]
layoutBackgroundHeaderSpace = false
showWordCount = false
showAuthor = false
editAppendPath = false
showDate = false
showDraftLabel = false
showTags = false
showPagination = true
showHeadingAnchors = false
showCategories = false
showReadingTime = false
layoutBackgroundBlur = false

[term]
layoutBackgroundHeaderSpace = true
showTableOfContents = true
cardViewScreenWidth = false
showViews = false
groupByYear = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[header]
layout = "basic"

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
cardView = true
cardViewScreenWidth = true
homepageImage = "img/falling-leaves-in-the-city.1920x1080.mp4"

[buymeacoffee]

[listDefaults]
groupByYear = false
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false

[taxonomy]
layoutBackgroundHeaderSpace = true
showTableOfContents = false
showTermCount = true
showViews = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[favicon]
svg = "favicon.svg"
png32 = "favicon-32x32.png"
png16 = "favicon-16x16.png"
appleTouch = "apple-touch-icon.png"
manifest = "site.webmanifest"

[sitemap]
excludedKinds = ["taxonomy", "term"]

[article]
seriesOpened = false
layoutBackgroundHeaderSpace = true
showTableOfContents = true
showEdit = false
showWordCount = true
showAuthor = true
editAppendPath = true
showZenMode = false
showDate = true
showTaxonomies = false
showCategoriesInSecondaryColor = false
invertPagination = false
showDraftLabel = true
showDateUpdated = false
showViews = false
showBreadcrumbs = true
showTags = true
showHero = false
showPagination = true
showHeadingAnchors = true
showCategories = true
showDateOnlyInArticle = false
showAuthorsBadges = false
showReadingTime = true
layoutBackgroundBlur = true
showLikes = false

[_images]
hotlinkFeatureImage = true
disableImageOptimizationMD = false
disableImageOptimization = false

[fathomAnalytics]

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[verification]

[seo]

[list]
layoutBackgroundHeaderSpace = true
showTableOfContents = true
cardViewScreenWidth = false
showCards = false
showSummary = false
showViews = false
groupByYear = true
showBreadcrumbs = true
cardView = false
showHero = false
constrainItemsWidth = false
orderByWeight = false
layoutBackgroundBlur = true
showLikes = false
