disableImageOptimization = false
defaultAppearance = "dark"
enableCodeCopy = false
autoSwitchAppearance = true
mainSections = ["writeups", "blog", "achievements", "ctfs", "projects"]
disableTextInHeader = false
colorScheme = "slate"
enableSearch = true
fingerprintAlgorithm = "sha512"
hotlinkFeatureImage = false
giteaDefaultServer = "https://git.fsfe.org"
disableImageOptimizationMD = false
forgejoDefaultServer = "https://v11.next.forgejo.org"
enableA11y = false
replyByEmail = false
enableStructuredBreadcrumbs = false

[selineAnalytics]

[umamiAnalytics]

[rssnext]

[advertisement]

[firebase]

[term]
layoutBackgroundHeaderSpace = true
showTableOfContents = true
cardViewScreenWidth = false
showViews = false
groupByYear = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[header]
layout = "basic"

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 5
showMoreLink = false
cardView = false
cardViewScreenWidth = false

[buymeacoffee]

[taxonomy]
layoutBackgroundHeaderSpace = true
showTableOfContents = false
showTermCount = true
showViews = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[article]
seriesOpened = false
layoutBackgroundHeaderSpace = true
showTableOfContents = false
showEdit = false
showWordCount = true
showAuthor = true
editAppendPath = true
showZenMode = false
showDate = true
showTaxonomies = false
showCategoriesInSecondaryColor = false
invertPagination = false
showDraftLabel = true
showDateUpdated = false
showViews = false
showBreadcrumbs = false
showTags = true
showHero = false
showPagination = true
showHeadingAnchors = true
showCategories = true
showDateOnlyInArticle = false
showAuthorsBadges = false
showReadingTime = true
layoutBackgroundBlur = true
showLikes = false

[fathomAnalytics]

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[verification]

[seo]

[list]
layoutBackgroundHeaderSpace = true
showTableOfContents = false
cardViewScreenWidth = false
showCards = false
showSummary = false
showViews = false
groupByYear = true
showBreadcrumbs = false
cardView = false
showHero = false
constrainItemsWidth = false
orderByWeight = false
layoutBackgroundBlur = true
showLikes = false
