disableImageOptimization = false
defaultAppearance = "dark"
enableCodeCopy = false
autoSwitchAppearance = true
mainSections = ["writeups", "blog", "achievements", "ctfs", "projects"]
disableTextInHeader = false
colorScheme = "congo"
enableSearch = true
fingerprintAlgorithm = "sha512"
hotlinkFeatureImage = false
giteaDefaultServer = "https://git.fsfe.org"
disableImageOptimizationMD = false
forgejoDefaultServer = "https://v11.next.forgejo.org"
backgroundImageWidth = 2560
enableA11y = false
replyByEmail = false
enableStructuredBreadcrumbs = false

[selineAnalytics]

[umamiAnalytics]

[taxonomyDefaults]
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showTermCount = false

[fonts]
fontHeading = ""
fontHeadingFile = "/fonts/moistlyvengionsdemo-regular.otf"
fontBodyFile = "/fonts/moistlyvengionsdemo-regular.otf"

[rssnext]

[advertisement]

[firebase]

[general]
enableSearch = true
enableStructuredBreadcrumbs = true
highlightCurrentMenuArea = true
fingerprintAlgorithm = "sha512"
smartTOC = false
smartTOCHideUnfocusedChildren = false

[articleDefaults]
layoutBackgroundHeaderSpace = false
showWordCount = false
showAuthor = false
editAppendPath = false
showDate = false
showDraftLabel = false
showTags = false
showPagination = true
showHeadingAnchors = false
showCategories = false
showReadingTime = false
layoutBackgroundBlur = false

[term]
layoutBackgroundHeaderSpace = true
showTableOfContents = true
cardViewScreenWidth = false
showViews = false
groupByYear = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[header]
layout = "fixed-fill-blur"

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
cardView = true
cardViewScreenWidth = true
homepageImage = "img/falling-leaves-in-the-city.1920x1080.mp4"

[buymeacoffee]

[listDefaults]
groupByYear = false
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false

[taxonomy]
layoutBackgroundHeaderSpace = true
showTableOfContents = false
showTermCount = true
showViews = false
showBreadcrumbs = false
cardView = false
showHero = false
layoutBackgroundBlur = true
showLikes = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[article]
seriesOpened = false
layoutBackgroundHeaderSpace = true
showTableOfContents = false
showEdit = false
showWordCount = true
showAuthor = true
editAppendPath = true
showZenMode = false
showDate = true
showTaxonomies = false
showCategoriesInSecondaryColor = false
invertPagination = false
showDraftLabel = true
showDateUpdated = false
showViews = false
showBreadcrumbs = false
showTags = true
showHero = false
showPagination = true
showHeadingAnchors = true
showCategories = true
showDateOnlyInArticle = false
showAuthorsBadges = false
showReadingTime = true
layoutBackgroundBlur = true
showLikes = false

[fathomAnalytics]

[verification]

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[seo]

[list]
layoutBackgroundHeaderSpace = true
showTableOfContents = false
cardViewScreenWidth = false
showCards = false
showSummary = false
showViews = false
groupByYear = true
showBreadcrumbs = false
cardView = false
showHero = false
constrainItemsWidth = false
orderByWeight = false
layoutBackgroundBlur = true
showLikes = false
