[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.163.0"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 404
